specversion = "0.2"

[[capability]]
resource = "keyvalue.azblob"
name = "my-container"
    [capability.configs]
    AZURE_STORAGE_ACCOUNT = "${azapp.AZURE_STORAGE_ACCOUNT}"
    AZURE_STORAGE_KEY = "${azapp.AZURE_STORAGE_KEY}"

[[capability]]
resource = "messaging.nats"
name = "my-messaging"
    [capability.configs]
    NATS_CREDS = "${azapp.NATS_CREDS}"